business_fact:
  columns:
    - name: order_number
      type: int
      nullable: false
    - name: order_date
      type: date
      nullable: false
    - name: storekey
      type: int
      nullable: false
    - name: productkey
      type: int
      nullable: false
    - name: quantity
      type: int
      nullable: false
    - name: total_quantity
      type: int
      nullable: true
    - name: order_count
      type: int
      nullable: true
    - name: sales_amount
      type: float
      nullable: true
    - name: revenue_local
      type: float
      nullable: true
    - name: revenue_usd
      type: float
      nullable: true
    - name: metric_1
      type: float
      nullable: true
    - name: metric_2
      type: float
      nullable: true
    - name: state_snapshot
      type: str
      nullable: true
